<?php
/**
 * Create Payment Table
 */
function pm_table_install() {
	global $wpdb;
	
	$table_name = $wpdb->prefix . "payments";
	$payments_db_ver = '1.0.2';
	$installed_ver = get_option ( "payments_db_version" );
	if ($installed_ver != $payments_db_ver) {
		$sql = "CREATE TABLE " . $table_name . " (
			id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
			date TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
			buyer_email VARCHAR(127) CHARACTER SET ASCII NOT NULL,
			txnid VARCHAR(127) CHARACTER SET ASCII NOT NULL,
			donation_website VARCHAR(200) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
			donation_linktext VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
			itemname VARCHAR(255) NOT NULL default '',
			itemnumber varchar(50),
			payment_gross DECIMAL(12,2),
			payment_fee DECIMAL(12,2),
			mc_gross DECIMAL(12,2) NOT NULL,
			mc_fee DECIMAL(12,2) NOT NULL,
			mc_currency varchar(5) NOT NULL default '',
			exchange_rate DECIMAL(20,8) NOT NULL default 1.00,
			custom varchar(255),
			user_memo varchar(255),
			base_days int(10),
			base_currency varchar(255) NOT NULL default '',
			base_amount DECIMAL(12,2) NOT NULL default 1,
			active ENUM('0', '1') DEFAULT '0'
					);";
		require_once (ABSPATH . 'wp-admin/includes/upgrade.php');
		dbDelta ( $sql );
		update_option ( "payments_db_version", $payments_db_ver );
	}
	
	$table_name = $wpdb->prefix . "payitems";
	if ($wpdb->get_var ( "SHOW TABLES LIKE '$table_name'" ) != $table_name) {
		$sql = "CREATE TABLE " . $table_name . " (
			itemnumber INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
			itemname VARCHAR(255) NOT NULL default'',
			custom varchar(255) NOT NULL default '',
			memo varchar(255)
		);";
		require_once (ABSPATH . 'wp-admin/includes/upgrade.php');
		dbDelta ( $sql );
		add_option ( "payitems_db_version", "1.0" );
	}
}

/**
 * Administration Menu
 */
function donators_menu() {
	if (function_exists ( 'add_menu_page' )) {
		add_menu_page ( __ ( 'Sponsors', 'wp-donators' ), __ ( 'Sponsors', 'wp-donators' ), 10, 'wp-donators/payment-manager.php' , '', plugins_url('wp-donators/images/wp-donators.png'));
	}
	if (function_exists ( 'add_submenu_page' )) {
		add_submenu_page ( 'wp-donators/payment-manager.php', __ ( 'Option', 'wp-donators' ), __ ( 'Option', 'wp-donators' ), 10, 'wp-donators/payment-manager.php' );
		add_submenu_page ( 'wp-donators/payment-manager.php', __ ( 'IPN Log', 'wp-donators' ), __ ( 'IPN Log', 'wp-donators' ), 10, 'wp-donators/report.php' );
		//		add_submenu_page( 'wp-donators/payment-manager.php' , __('Donations Items', 'wp-donators'), __('Donations Item', 'wp-donators'),10, 'wp-donators/add_gui.php');
	}
}

/**
 * output to the <head> section of the page
 */
function WD_header() {
	$hHead = "\n" . "<!-- Start Of Script Generated By WP-Donators -->" . "\n";
	$hHead .= "<style type=\"text/css\">
							.ui-tabs .ui-tabs-nav li a {padding: 3px; }
							.ui-tabs .ui-tabs-panel {padding: 5px;}
	</style>";
	$hHead .= "<!-- End Of Script Generated By WP-Donators -->" . "\n";
	print ( $hHead );
}

/**
 * Get self url
 *
 * @return self_url
 */
function get_self_url() {
	$full_url = 'http';
	$script_name = '';
	if (isset ( $_SERVER ['REQUEST_URI'] )) {
		$script_name = $_SERVER ['REQUEST_URI'];
	} else {
		$script_name = $_SERVER ['PHP_SELF'];
		if ($_SERVER ['QUERY_STRING'] > ' ') {
			$script_name .= '?' . $_SERVER ['QUERY_STRING'];
		}
	}
	if (isset ( $_SERVER ['HTTPS'] ) && $_SERVER ['HTTPS'] == 'on') {
		$full_url .= 's';
	}
	$full_url .= '://';
	if ($_SERVER ['SERVER_PORT'] != '80') {
		$full_url .= $_SERVER ['HTTP_HOST'] . ':' . $_SERVER ['SERVER_PORT'] . $script_name;
	} else {
		$full_url .= $_SERVER ['HTTP_HOST'] . $script_name;
	}
	return $full_url;
}
?>